version: "3.8"

services:

  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=ahmed
    volumes:
      - ./db_data:/var/lib/mysql

  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      RAILS_ENV: development
      MYSQL_DATABASE_NAME: BlogApplication_development
      MYSQL_DATABASE_USER: root
      MYSQL_DATABASE_PASSWORD:
      DATABASE_HOST: database

volumes:
  db_data: