default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  port: 3306
  host: <%= ENV['DB_HOST'] || 'database' %>
  database: <%= ENV['DB_NAME'] || 'BlogApplication_development' %>
  username: <%= ENV['DB_USER'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] || 'password' %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default