default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 10000
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: BlogApplication_development

test:
  <<: *default
  database: BlogApplication_test

production:
  <<: *default
  database: BlogApplication_production
  username: BlogApplication
  password: <%= ENV['BLOGAPPLICATION_DATABASE_PASSWORD'] %>