default: &default
  adapter: mysql2
  encoding: utf8mb4
  database: BlogApplication_development
  username: root
  password:
  host: database
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default